#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/junyharang;MODE=MySQL;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  #      settings:
  #        web-allow-others: true
  #
  #  datasource:
  #    url: jdbc:log4jdbc:h2:~/Programming/side_project/giggal-pepole/BackEnd/GiggalPeopleBackOffice/h2-db/giggal-people?serverTimezone=UTC&characterEncoding=UTF-8;MODE=MySQL;
  #    url: jdbc:log4jdbc:h2:~/giggal-people?serverTimezone=UTC&characterEncoding=UTF-8;MODE=MySQL;
  #    username: sa
  #    password:
  ##    driver-class-name: org.h2.Driver
  #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  datasource:
    #    url: jdbc:log4jdbc:h2:~/Programming/side_project/giggal-pepole/BackEnd/GiggalPeopleBackOffice/h2-db/giggal-people?serverTimezone=UTC&characterEncoding=UTF-8;MODE=MySQL;
    url: jdbc:log4jdbc:mariadb://192.168.0.2:1000/giggal_back_office?serverTimezone=UTC&characterEncoding=UTF-8;
    username: giggal
    password: Giggal369!@#
    #    driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  sql:
    init:
      mode: always
      schema-locations: classpath:init/database/schema.sql
      data-locations: classpath:init/database/data.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true