server:
  name: Giggal-Total-Back-Office
  port: 9999

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
    syntax-highlight:
      theme: nord
    version: v1.1.0
    display-request-duration: true

  cache:
    disabled: true

  paths-to-match:
    - /api/**