spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://192.168.20.10:1000/giggal_total_back_office?serverTimezone=UTC&characterEncoding=UTF-8;
    username: giggal
    password: Giggal369!@#
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  sql:
    init:
      mode: always
      schema-locations: classpath:init/database/schema.sql
      data-locations: classpath:init/database/data.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true