version: "3"

services:
  giggal-total-back-office-api-blue-a:
    image: giggal-people/total-back-office-blue-a:latest
    container_name: giggal-people-total-back-office-blue-a
    hostname: giggal-people-total-back-office-blue-a
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - LANG=ko_KR.UTF-8

    build:
      context: ..
      dockerfile: /data/deploy/giggal-total-back-office/deploy/docker/bak-Dockerfile

    restart: unless-stopped
    ports:
      - "8080:8080"
